modules = [
    '@rpgjs/default-gui',
    './main/modules/title-screen',
    'rpgjs-character-select',
    './main',
    './spritesheets'
]

spritesheetDirectories = [
    'lpc/heads',
    'lpc/bodies',
    'lpc/accessories',
    'lpc/torso',
    'lpc/legs',
    'lpc/hair',
    'lpc/ears',
]

[titleScreen]
    title = 'My game'
    music = 'menu'
    mongodb = '$ENV:VITE_MONGODB_URL'

[start]
    map = 'world'
    hitbox = [32, 32]

[characterSelect]
  actors = [
    'human',
    'elf',
    'vampire',
  ]

[inputs.up]
    name = "up"
    repeat = true
    bind = ["up", "w"]

[inputs.down]
    name = "down"
    repeat = true
    bind = ["down", "s"]


[inputs.right]
    name = "right"
    repeat = true
    bind = ["right", "d"]

[inputs.left]
    name = "left"
    repeat = true
    bind = ["left", "a"]

[inputs.slash]
    name = "slash"
    repeat = false
    bind = "f"

[inputs.shoot]
    name = "shoot"
    repeat = false
    bind = "g"